limit_req_zone $binary_remote_addr zone=msg_clone_http:10m rate=5r/s;
limit_req_zone $binary_remote_addr zone=msg_clone_ws:10m rate=6r/m;
limit_conn_zone $binary_remote_addr zone=msg_clone_per_ip:10m;
limit_conn_zone $server_name zone=msg_clone_total:1m;
